<?php
use Icinga\Module\Monitoring\Object\Host;
use Icinga\Module\Monitoring\Object\Service;
?>
<?php $showService = $object->getType() === $object::TYPE_SERVICE ?>
<?php if (!$this->compact): ?>
<?= $tabs ?>
<?php endif ?>
<table class="objectstate">
  <tr class="state <?= $this->monitoringState($object, 'host') ?><?= $object->host_handled ? ' handled' : '' ?>">
    <td class="state"<?= $showService ? '' : ' rowspan="2"' ?> title="<?= sprintf($this->translate('%s since %s', 'datetime.title'), strtoupper(Host::getStateText($object->host_state)), date('Y-m-d H:i:s', $object->host_last_state_change)); ?>">
      <strong><?= strtoupper(Host::getStateText($object->host_state, true)) ?></strong><br />
      <?= $this->prefixedTimeSince($object->host_last_state_change, true) ?>
    </td>
    <td><b><?= $this->escape($object->host_name) ?></b><?php
 if ($object->host_address && $object->host_address !== $object->host_name): ?>
 <br><?= $this->escape($object->host_address) ?>
<?php endif ?>
    </td>
  </tr>
<?php if ($showService): ?>
  <tr class="state <?= $this->monitoringState($object, 'service') ?><?= $object->service_handled ? ' handled' : '' ?>">
    <td class="state" title="<?= sprintf($this->translate('%s since %s', 'datetime.title'), strtoupper(Service::getStateText($object->service_state, true)), date('Y-m-d H:i:s', $object->service_last_state_change)); ?>">
      <strong><?= $this->translate($this->util()->getServiceStateName($object->service_state)) ?></strong><br />
      <?= $this->prefixedTimeSince($object->service_last_state_change, true) ?>
    </td>
    <td><b><?= $this->translate('Service') ?>: <?= $this->escape($object->service_description) ?></b>

    <?= $this->render('show/components/statusIcons.phtml') ?>

</td>
  </tr>
<?php else: ?>
  <tr><td><!--<b>Host state</b>-->&nbsp;</td></tr>
<?php endif ?>
</table>
