<?php

// We are not interested in notifications for OK or pending objects
if (in_array((int) $object->state, array(0, 99))) {
    return;
}

?>
<tr>
  <th><?= $this->translate('Notifications') ?></th>
  <td>
<?php

if ($object->current_notification_number > 0) {
    echo (
        (int) $object->current_notification_number === 1
    ) ? sprintf(
        $this->translate('A notication has been sent for this issue %s ago'),
        $this->timeSince($object->last_notification)
    ) : sprintf(
        $this->translate('%s notications have been sent for this issue')
        .'<br />'.
        $this->translate('The last one occured %s ago'),
        $object->current_notification_number,
        $this->timeSince($object->last_notification)
    );
} else {
    echo $this->translate('No notification has been sent for this issue');
}
?>
  </td>
</tr>
