<?php

// We are not interested in notifications for OK or pending objects
if (in_array((int) $object->state, array(0, 99))) {
    return;
}

?>
<tr>
  <th><?= $this->translate('Notifications') ?></th>
  <td>
<?php

if ($object->current_notification_number > 0) {
    $last_notification = $this->dateTimeRenderer($object->last_notification)->render(
        $this->translate('on %s', 'datetime'),
        $this->translate('at %s', 'time'),
        $this->translate('%s ago', 'timespan')
    );
    echo (
        (int) $object->current_notification_number === 1
    ) ? sprintf(
        $this->translate('A notication has been sent for this issue %s'),
        $last_notification
    ) : sprintf(
        $this->translate('%s notications have been sent for this issue')
        .'<br />'.
        $this->translate('The last one occured %s'),
        $object->current_notification_number,
        $last_notification
    );
} else {
    echo $this->translate('No notification has been sent for this issue');
}
?>
  </td>
</tr>
