<?php
use Icinga\Module\Monitoring\Object\Host;
use Icinga\Module\Monitoring\Object\Service;
?>
<?php if (false === $this->compact): ?>
<div class="controls">
  <?= $this->tabs->render($this); ?>
  <div style="margin: 1em" class="dontprint">
    <?= $this->translate('Sort by'); ?> <?= $this->sortControl->render($this); ?>
    <?php if (! $this->filterEditor): ?>
        <?= $this->filterPreview ?>
    <?php endif; ?>
  </div>
  <?= $this->widget('limiter', array('url' => $this->url, 'max' => $downtimes->count())); ?>
  <?= $this->paginationControl($downtimes, null, null, array('preserve' => $this->preserve)); ?>
</div>
<?php endif ?>

<div class="content">
<?= $this->filterEditor ?>
<?php if (count($downtimes) === 0): ?>
  <?= $this->translate('No active downtimes'); ?>
</div>
<?php return; endif ?>

  <table data-base-target="_next" class="action">
    <tbody>
    <?php foreach ($downtimes as $downtime): ?>
    <?php
      if (isset($downtime->service)) {
          $stateName = Service::getStateText($downtime->service_state, true);
      } else {
          $stateName = Host::getStateText($downtime->host_state, true);
      }
      $now = time();
      if ($downtime->is_flexible == 1) {
          if ($downtime->scheduled_start <= $now && $now <= $downtime->scheduled_end) {
              $stateTitle = $this->translate('Flexible Downtime Expires');
              $downtimeDate = (int) (($downtime->is_in_effect == 1)
                  ? $downtime->end
                  : $downtime->scheduled_end
              );
              $downtimeText = $this->timePointFuture($downtimeDate);
              $downtimeDate = sprintf($this->translate('at %s'), date('Y-m-d H:i:s', $downtimeDate));
          } else {
              $stateTitle = $this->translate('Flexible Downtime Scheduled');
              $downtimeText = $downtimeDate = sprintf(
                  $this->translate('between %s and %s'),
                  date('Y-m-d H:i:s', $downtime->scheduled_start),
                  date('Y-m-d H:i:s', $downtime->scheduled_end)
              );
          }
      } elseif ($downtime->start <= $now && $now <= $downtime->end) {
          $stateTitle = $this->translate('Downtime Expires');
          $downtimeDate = (int) $downtime->end;
          $downtimeText = $this->timePointFuture($downtimeDate);
          $downtimeDate = sprintf($this->translate('at %s'), date('Y-m-d H:i:s', $downtimeDate));
      } else {
          $stateTitle = $this->translate('Downtime Starts');
          $downtimeDate = (int) $downtime->start;
          $downtimeText = $this->timePointFuture($downtimeDate);
          $downtimeDate = sprintf($this->translate('at %s'), date('Y-m-d H:i:s', $downtimeDate));
      }
    ?>
      <tr class="state <?= $stateName . ($downtime->is_in_effect ? ' handled' : '') ?>">
        <td class="state" title="<?= sprintf($this->translate('%s %s'), $stateTitle, $downtimeDate) ?>">
          <strong><?= $stateTitle ?></strong>
          <br>
            <?= $downtimeText ?>
        </td>
        <td>
        <?php if (isset($downtime->service)): ?>
          <a href="<?= $this->href('monitoring/service/show', array(
            'host'      => $downtime->host,
            'service'   => $downtime->service
          )); ?>">
            <?= $downtime->service; ?>
          </a>
          <small>
            <?= $this->translate('on'); ?> <?= $downtime->host; ?>
          </small>
        <?php else: ?>
          <a href="<?= $this->href('monitoring/host/show', array(
            'host' => $downtime->host
          )); ?>">
            <?= $downtime->host; ?>
          </a>
        <?php endif ?>
          <br>
          <?= $this->icon('comment'); ?> [<?= $downtime->author; ?>] <?= $downtime->comment; ?>
          <br>
          <small>
        <?php if ($downtime->is_flexible): ?>
          <?php if ($downtime->is_in_effect): ?>
            <?= sprintf(
              $this->translate('This flexible downtime was started on %s at %s and lasts for %s until %s at %s.'),
              date('d.m.y', $downtime->start),
              date('H:i', $downtime->start),
              $this->format()->duration($downtime->duration),
              date('d.m.y', $downtime->end),
              date('H:i', $downtime->end)
            ); ?>
          <?php else: ?>
            <?= sprintf(
              $this->translate('This flexible downtime has been scheduled to start between %s - %s and to last for %s.'),
              date('d.m.y H:i', $downtime->scheduled_start),
              date('d.m.y H:i', $downtime->scheduled_end),
              $this->format()->duration($downtime->duration)
            ); ?>
          <?php endif ?>
        <?php else: ?>
          <?php if ($downtime->is_in_effect): ?>
            <?= sprintf(
              $this->translate('This fixed downtime was started on %s at %s and expires on %s at %s.'),
              date('d.m.y', $downtime->start),
              date('H:i', $downtime->start),
              date('d.m.y', $downtime->end),
              date('H:i', $downtime->end)
            ); ?>
          <?php else: ?>
            <?= sprintf(
              $this->translate('This fixed downtime has been scheduled to start on %s at %s and to end on %s at %s.'),
              date('d.m.y', $downtime->scheduled_start),
              date('H:i', $downtime->scheduled_start),
              date('d.m.y', $downtime->scheduled_end),
              date('H:i', $downtime->scheduled_end)
            ); ?>
          <?php endif ?>
        <?php endif ?>
          </small>
        </td>
        <td style="width: 2em" data-base-target="self">
          <?php
          $delDowntimeForm = clone $delDowntimeForm;
          $delDowntimeForm->populate(array('downtime_id' => $downtime->id, 'redirect' => $this->url));
          if (! isset($downtime->service)) {
            $delDowntimeForm->setAction($this->url('monitoring/host/delete-downtime', array('host' => $downtime->host)));
          } else {
            $delDowntimeForm->setAction($this->url('monitoring/service/delete-downtime', array('host' => $downtime->host, 'service' => $downtime->service)));
          }
          echo $delDowntimeForm;
          ?>
        </td>
      </tr>
<?php endforeach ?>
    </tbody>
  </table>
</div>
