<div class="controls">
    <?= $this->tabs->showOnlyCloseButton() ?>
</div>
<div class="content">
    <h1><?= $title ?> <?= $this->icon('help', $form->getHelp()) ?></h1>
    <?php if ((bool) $programStatus->notifications_enabled === false): ?>
    <div>
        <?= $this->translate('Host and service notifications are already disabled.') ?>
        <?php if ($this->programStatus->disable_notif_expire_time) {
            printf(
                $this->translate('Notifications will be re-enabled <strong>%s</strong>.'),
                $this->timeUntil($this->programStatus->disable_notif_expire_time)
            );
        } ?>
    </div>
    <?php else: ?>
    <?= $form ?>
    <?php endif ?>
</div>
